export const ERROR_CODES = {
	NO_SESSION: "NO_SESSION",
	INVALID_SESSION: "INVALID_SESSION",
	FINGERPRINT_MISMATCH: "FINGERPRINT_MISMATCH",
	INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
	INVALID_USER_ID: "INVALID_USER_ID",
	INVALID_JSON: "INVALID_JSON",
	INVALID_ROLE: "INVALID_ROLE",
	MISSING_REASON: "MISSING_REASON",
	INVALID_EXPIRATION: "INVALID_EXPIRATION",
	OPERATION_FAILED: "OPERATION_FAILED",
	SELF_ROLE_CHANGE_FORBIDDEN: "SELF_ROLE_CHANGE_FORBIDDEN",
	SELF_BAN_FORBIDDEN: "SELF_BAN_FORBIDDEN",
	CANNOT_BAN_ADMIN: "CANNOT_BAN_ADMIN",
	NOT_IMPERSONATION_SESSION: "NOT_IMPERSONATION_SESSION",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function jsonError(status: number, error: string, code: ErrorCode): Response {
	return Response.json(
		{ error, code },
		{ status, headers: { "Content-Type": "application/json" } }
	);
}
